// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx4r0PdLlUFSw5G19dyYsRGMdeRZbLoM',
    appId: '1:380975477085:web:4f5afeb2c6e1500a06f8b4',
    messagingSenderId: '380975477085',
    projectId: 'hol-loc-app',
    authDomain: 'hol-loc-app.firebaseapp.com',
    storageBucket: 'hol-loc-app.appspot.com',
    measurementId: 'G-W7MSNQ1ZBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCJLoX6wIB48t43MHsgBiHSB-XcGpk-A',
    appId: '1:380975477085:android:69800e486ae13a0106f8b4',
    messagingSenderId: '380975477085',
    projectId: 'hol-loc-app',
    storageBucket: 'hol-loc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBt_HQWyM7sJRWkTm7qtd_TGq0bgEZ0U',
    appId: '1:380975477085:ios:7da78da517c2d68d06f8b4',
    messagingSenderId: '380975477085',
    projectId: 'hol-loc-app',
    storageBucket: 'hol-loc-app.appspot.com',
    iosClientId: '380975477085-8lhn8pkl4amf31m66ukbbpsu989q88ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.holLocApp',
  );
}
